name: 'Install dependencies'
description: 'Set up Python and install Poetry'

inputs:
  python-version: 
    required: true
    description: "Python version to use"
    default: "3.12"
  runner-os:
    required: true
    description: "OS used by the runner"
    default: "ubuntu-22.04"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v4
      with:
        path: |
          ~/.local
          ~/.config
        key: poetry-${{ inputs.runner-os }}-${{ inputs.python-version }}

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
        # fixed version of poetry to avoid conflicts with the
        # lack of freeze-dependencies for poetry 2.0.0
        version: "1.8.5"
