name: 'Install dependencies'
description: 'Install Python library dependencies using Poetry'

inputs:
  python-version: 
    required: true
    description: "Python version to use"
    default: "3.12"
  runner-os:
    required: true
    description: "OS used by the runner"
    default: "ubuntu-22.04"

runs:
  using: composite
  steps:
    - uses: pantos-io/ci-workflows/.github/actions/install-poetry@v1
      with:
        python-version: ${{ inputs.python-version }}
        runner-os: ${{ inputs.runner-os }}

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.venv
        key: venv-${{ inputs.runner-os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --without dev --no-interaction --no-root
